Exception on /login [GET]
Traceback (most recent call last):
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Raghu Rohith\adaptive\app\routes.py", line 20, in login
    if current_user.is_authenticated:
NameError: global name 'current_user' is not defined
Exception on /login [GET]
Traceback (most recent call last):
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Raghu Rohith\adaptive\app\routes.py", line 20, in login
    if current_user.is_authenticated:
NameError: global name 'current_user' is not defined
Exception on /login [GET]
Traceback (most recent call last):
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Raghu Rohith\adaptive\app\routes.py", line 20, in login
    if current_user.is_authenticated:
NameError: global name 'current_user' is not defined
Exception on /login [GET]
Traceback (most recent call last):
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Raghu Rohith\adaptive\app\routes.py", line 20, in login
    if current_user.is_authenticated:
NameError: global name 'current_user' is not defined
Exception on /login [GET]
Traceback (most recent call last):
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Raghu Rohith\adaptive\app\routes.py", line 20, in login
    if current_user.is_authenticated:
NameError: global name 'current_user' is not defined
Exception on /login [POST]
Traceback (most recent call last):
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Raghu Rohith\adaptive\app\routes.py", line 25, in login
    user = User.query.filter_by(username=form.username.data).first()
NameError: global name 'User' is not defined
Exception on /login [POST]
Traceback (most recent call last):
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Raghu Rohith\adaptive\app\routes.py", line 27, in login
    if user is None or not user.check_password(form.password.data):
AttributeError: 'User' object has no attribute 'check_password'
Exception on /login [POST]
Traceback (most recent call last):
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Raghu Rohith\adaptive\app\routes.py", line 27, in login
    if user is None or not user.check_password(form.password.data):
AttributeError: 'User' object has no attribute 'check_password'
Exception on /user/susan [GET]
Traceback (most recent call last):
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Raghu Rohith\adaptive\app\routes.py", line 70, in before_request
    current_user.last_seen = datetime.utcnow()
NameError: global name 'datetime' is not defined
Exception on / [GET]
Traceback (most recent call last):
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Raghu Rohith\adaptive\app\routes.py", line 70, in before_request
    current_user.last_seen = datetime.utcnow()
NameError: global name 'datetime' is not defined
Exception on / [GET]
Traceback (most recent call last):
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2087, in preprocess_request
    rv = func()
  File "C:\Users\Raghu Rohith\adaptive\app\routes.py", line 70, in before_request
    current_user.last_seen = datetime.utcnow()
NameError: global name 'datetime' is not defined
Exception on /user/sumanth [GET]
Traceback (most recent call last):
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Raghu Rohith\adaptive\app\routes.py", line 66, in user
    return render_template('user.html', user=user, posts=posts)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Raghu Rohith\adaptive\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Raghu Rohith\adaptive\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Raghu Rohith\adaptive\app\templates\base.html", line 47, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Raghu Rohith\adaptive\app\templates\user.html", line 13, in block "app_content"
    <p><a href="{{ url_for('edit_profile') }}">Edit your profile</a></p>
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'user' instead?
Exception on /user/sumanth [GET]
Traceback (most recent call last):
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Raghu Rohith\adaptive\app\routes.py", line 66, in user
    return render_template('user.html', user=user, posts=posts)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Raghu Rohith\adaptive\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Raghu Rohith\adaptive\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Raghu Rohith\adaptive\app\templates\base.html", line 47, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Raghu Rohith\adaptive\app\templates\user.html", line 13, in block "app_content"
    <p><a href="{{ url_for('edit_profile') }}">Edit your profile</a></p>
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'user' instead?
Exception on /user/sumanth [GET]
Traceback (most recent call last):
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Raghu Rohith\adaptive\app\routes.py", line 66, in user
    return render_template('user.html', user=user, posts=posts)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Raghu Rohith\adaptive\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Raghu Rohith\adaptive\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Raghu Rohith\adaptive\app\templates\base.html", line 47, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Raghu Rohith\adaptive\app\templates\user.html", line 13, in block "app_content"
    <p><a href="{{ url_for('edit_profile') }}">Edit your profile</a></p>
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'user' instead?
Exception on /login [POST]
Traceback (most recent call last):
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Raghu Rohith\adaptive\app\routes.py", line 36, in login
    usertime = Usertime(user_id=user.id ,time_loggedin= datetime.utcnow())
NameError: global name 'Usertime' is not defined
Exception on /login [POST]
Traceback (most recent call last):
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\raghur~1\envs\hellow~1\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Raghu Rohith\adaptive\app\routes.py", line 36, in login
    usertime = Usertime(user_id=user.id ,time_loggedin= datetime.utcnow())
NameError: global name 'Usertime' is not defined
